In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('../datasets/desastres_naturales/Climate-related_Disasters_Frequency_normalizado.csv',sep=';')
df

,Unnamed: 0,objectid,pais,iso2,pais_iso,indicador,code,unidad,fuente,1980,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,0,1,"Afghanistan, Islamic Rep. of",AF,AFG,Drought,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1,2,"Afghanistan, Islamic Rep. of",AF,AFG,Extreme temperature,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,3,"Afghanistan, Islamic Rep. of",AF,AFG,Flood,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",1.0,...,6.0,4.0,2.0,1.0,4.0,1.0,3.0,6.0,5.0,2.0
3,3,4,"Afghanistan, Islamic Rep. of",AF,AFG,Landslide,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,3.0,1.0,0.0,4.0,0.0,2.0,2.0,1.0,1.0,1.0
4,4,5,"Afghanistan, Islamic Rep. of",AF,AFG,Storm,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,963,964,Zambia,ZM,ZMB,TOTAL,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0,1.0
964,964,965,Zimbabwe,ZW,ZWE,Drought,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
965,965,966,Zimbabwe,ZW,ZWE,Flood,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
966,966,967,Zimbabwe,ZW,ZWE,Storm,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
967,967,968,Zimbabwe,ZW,ZWE,TOTAL,ECFRF_NUM,Number of,"The Emergency Events Database (EM-DAT) , Centr...",0.0,...,0.0,2.0,2.0,1.0,1.0,2.0,0.0,2.0,0.0,2.0

In [7]:
col=['Unnamed: 0','objectid','iso2','code','unidad','fuente']

df.drop(columns=col,inplace=True)
df

,pais,pais_iso,indicador,1980,1981,1982,1983,1984,1985,1986,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,"Afghanistan, Islamic Rep. of",AFG,Drought,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,"Afghanistan, Islamic Rep. of",AFG,Extreme temperature,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"Afghanistan, Islamic Rep. of",AFG,Flood,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,4.0,2.0,1.0,4.0,1.0,3.0,6.0,5.0,2.0
3,"Afghanistan, Islamic Rep. of",AFG,Landslide,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,1.0,0.0,4.0,0.0,2.0,2.0,1.0,1.0,1.0
4,"Afghanistan, Islamic Rep. of",AFG,Storm,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Zambia,ZMB,TOTAL,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0,1.0
964,Zimbabwe,ZWE,Drought,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
965,Zimbabwe,ZWE,Flood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
966,Zimbabwe,ZWE,Storm,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
967,Zimbabwe,ZWE,TOTAL,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,1.0,1.0,2.0,0.0,2.0,0.0,2.0

In [8]:
cols=['pais','pais_iso','indicador']

df1=pd.melt(df,id_vars=cols,var_name='anio',value_name='frecuencia')
df1

,pais,pais_iso,indicador,anio,frecuencia
0,"Afghanistan, Islamic Rep. of",AFG,Drought,1980,0.0
1,"Afghanistan, Islamic Rep. of",AFG,Extreme temperature,1980,0.0
2,"Afghanistan, Islamic Rep. of",AFG,Flood,1980,1.0
3,"Afghanistan, Islamic Rep. of",AFG,Landslide,1980,0.0
4,"Afghanistan, Islamic Rep. of",AFG,Storm,1980,0.0
...,...,...,...,...,...
40651,Zambia,ZMB,TOTAL,2021,1.0
40652,Zimbabwe,ZWE,Drought,2021,1.0
40653,Zimbabwe,ZWE,Flood,2021,0.0
40654,Zimbabwe,ZWE,Storm,2021,1.0
40655,Zimbabwe,ZWE,TOTAL,2021,2.0

In [9]:
df1.to_csv('../datasets/desastres_naturales/Climate-related_Disasters_Frequency_normalizado.csv',sep=';',index=False)